### ISSUE TITLE
Bug and Crashed

### ISSUE THREAD

**Issue by ZexKenden** [alvin0319/CustomItemLoader#10]
Hello I have found an issue

if u put this
can_always_eat: true
when I have a full food bar hunger you eating custom food they don't decrease1 only happen fully food bar hunger

Seconds Issue:
If you eating food when touch block you will get crashed in-game not an error, you can test out it. I have tested on pc.

**Comment by alvin0319** [comment]
First issue is correct, see Golden apple(or enchanted goleden apple).

but I checked second issue, I will fix soon

**Comment by alvin0319** [comment]
I can't find the problem, leave it as a wontfix.

**Comment by alvin0319** [comment]
This issue occurs when the item's texture has many pixels. Try to reduce pixels on texture.
