### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by XxGalaxy300** [alvin0319/CustomItemLoader#114]
Hello i cant start my server it says the API is Incomplete 
![20230219_151908](https://user-images.githubusercontent.com/125708368/219954093-ec075b15-902f-47b4-b7bb-aa4315c706a5.jpg)

**Comment by alvin0319** [comment]
You are using an outdated version.

**Comment by XxGalaxy300** [comment]
I have the newest V

**Comment by alvin0319** [comment]
https://github.com/alvin0319/CustomItemLoader/blob/master/plugin.yml#L5 Latest version uses 4.0.0 as API.

**Comment by XxGalaxy300** [comment]
How i install that?
