### ISSUE TITLE
Issue due to actuator update

### ISSUE THREAD

**Issue by vkamz597** [alvin0319/CustomItemLoader#117]
PMMP INFO

5.0.0-beta4
PHP 8.2
linux

[CustomItemLoader] Failed to load custom items: Failed to register item: Class "pocketmine\network\mcpe\convert\GlobalItemTypeDictionary" not found, disabling plugin to prevent any unintended behaviour...
2023-05-23 [18:09:54.801] [Server thread/CRITICAL]: InvalidArgumentException: "Failed to register item: Class "pocketmine\network\mcpe\convert\GlobalItemTypeDictionary" not found" (92) in "plugins/CustomItemLoader-api-pm5/src/alvin0319/CustomItemLoader/CustomItemManager" at line 87
--- Stack trace ---
  #0 plugins/CustomItemLoader-api-pm5/src/alvin0319/CustomItemLoader/CustomItemManager(101): alvin0319\CustomItemLoader\CustomItemManager->registerItem(object alvin0319\CustomItemLoader\item\CustomItem#59853)
  #1 plugins/CustomItemLoader-api-pm5/src/alvin0319/CustomItemLoader/CustomItemLoader(51): alvin0319\CustomItemLoader\CustomItemManager->registerDefaultItems(array[76])
  #2 pmsrc/src/plugin/PluginBase(118): alvin0319\CustomItemLoader\CustomItemLoader->onEnable()
  #3 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #4 pmsrc/src/Server(1388): pocketmine\plugin\PluginManager->enablePlugin(object alvin0319\CustomItemLoader\CustomItemLoader#39414)
  #5 pmsrc/src/Server(1032): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#39371)
  #6 pmsrc/src/PocketMine(334): pocketmine\Server->construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[9] /root/pm/, string[17] /root/pm/plugins/)
  #7 pmsrc/src/PocketMine(357): pocketmine\server()
  #8 pmsrc(11): require(string[53] phar:///root/pm/PocketMine-MP.phar/src/PocketMine.php)
--- Previous ---
Error: "Class "pocketmine\network\mcpe\convert\GlobalItemTypeDictionary" not found" (EXCEPTION) in "plugins/libItemRegistrar-master/src/alvin0319/libItemRegistrar/libItemRegistrar" at line 92
  #0 plugins/CustomItemLoader-api-pm5/src/alvin0319/CustomItemLoader/CustomItemManager(85): alvin0319\libItemRegistrar\libItemRegistrar->registerItem(object alvin0319\CustomItemLoader\item\CustomItem#59876, int 25266, true, string[19] custom:............)
  #1 plugins/CustomItemLoader-api-pm5/src/alvin0319/CustomItemLoader/CustomItemManager(101): alvin0319\CustomItemLoader\CustomItemManager->registerItem(object alvin0319\CustomItemLoader\item\CustomItem#59853)
  #2 plugins/CustomItemLoader-api-pm5/src/alvin0319/CustomItemLoader/CustomItemLoader(51): alvin0319\CustomItemLoader\CustomItemManager->registerDefaultItems(array[76])
  #3 pmsrc/src/plugin/PluginBase(118): alvin0319\CustomItemLoader\CustomItemLoader->onEnable()
  #4 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #5 pmsrc/src/Server(1388): pocketmine\plugin\PluginManager->enablePlugin(object alvin0319\CustomItemLoader\CustomItemLoader#39414)
  #6 pmsrc/src/Server(1032): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#39371)
  #7 pmsrc/src/PocketMine(334): pocketmine\Server->construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[9] /root/pm/, string[17] /root/pm/plugins/)
  #8 pmsrc/src/PocketMine(357): pocketmine\server()
  #9 pmsrc(11): require(string[53] phar:///root/pm/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by alvin0319** [comment]
Update your libItemRegistrar
