### ISSUE TITLE
Custom item does not work with custom crafting recipe

### ISSUE THREAD

**Issue by Adam1609** [alvin0319/CustomItemLoader#13]
I try adding custom item into crafting recipe, it worked at the beginning, but then I restarted the server it show unmapped item.

I also use TeamBixby's CustomCraft but it has the same error

**Comment by alvin0319** [comment]
It also have troble with CustomCraft, I will fix it as soon as possible.

**Comment by Adam1609** [comment]
The error seems to be continued, will it be fixed soon?

**Comment by alvin0319** [comment]
> The error seems to be continued, will it be fixed soon?

It also have trouble with CustomCraft, and I can't find the reason.

If I fix this error, I will close this issue.

**Comment by ElectroGamesYT** [comment]
Has this been fixed yet?

**Comment by alvin0319** [comment]
Closing this issue since I don't have any mind to fix this.
