### ISSUE TITLE
does your plugin work?

### ISSUE THREAD

**Issue by CortexAlexDEV** [alvin0319/CustomItemLoader#17]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CortexAlexDEV** [comment]
does your plugin work?

**Comment by alvin0319** [comment]
Works well, check my examples on [Example folder](https://github.com/alvin0319/CustomItemLoader/tree/master/example).
