### ISSUE TITLE
More explaination on creating resource pack

### ISSUE THREAD

**Issue by Adam1609** [alvin0319/CustomItemLoader#2]
I have installed it in like 26 minutes and try to use it. It is super great! But the only things I didn't know (although I read your wiki) is about changing an item's resource pack. Can you explain it more, like the argument of the command?

**Comment by alvin0319** [comment]
I added an example, can you try again?

**Comment by Adam1609** [comment]
It worked! Truly a magical plugin. Keep up a good work dude
