### ISSUE TITLE
Wrong item name

### ISSUE THREAD

**Issue by benda95280** [alvin0319/CustomItemLoader#23]
**Describe the bug**
Item is showed as item..justtest:hammer

**To Reproduce**
Used all command to create, add, and pack my ressources
Files used included

**Expected behavior**
Should show right item name => "Big Hammer"

**Actual behavior**
Item is showed as "item..justtest:hammer"

**Screenshots**
![Minecraft 20_04_2021 22_35_29](https://user-images.githubusercontent.com/1539408/115460614-c5736e00-a228-11eb-9489-2546169be40a.png)

**Version info (please complete the following information):**

 - OS: W10
 - PocketMine-MP Version: 1.16.220
 - CustomItemLoader Version: 2.0.2

**Additional context**
Config file used
[config.yml.zip](https://github.com/alvin0319/CustomItemLoader/files/6346538/config.yml.zip)
Ressource pack 
[test.mcpack.zip](https://github.com/alvin0319/CustomItemLoader/files/6346541/test.mcpack.zip)

**Comment by alvin0319** [comment]
try to edit your language file with your correct namespace and item name.

**Comment by alvin0319** [comment]
my plugin only provides en_US language file, if you are using other language you should add your language file to resource pack.

**Comment by benda95280** [comment]
Could you implement the generation of the text for all languages ?

**Comment by PJZ9n** [comment]
Although you may have already solved: Use `item.justtest:hammer=hammer` instead of `item.justtest=hammer` in en_US.lang.

And I think that supporting all languages depends on resource packs, not plugins.

For example create `ja_JP.lang` and it should work fine.
