### ISSUE TITLE
Armor Item

### ISSUE THREAD

**Issue by Nya-Enzo** [alvin0319/CustomItemLoader#24]
**Is your feature request related to a problem? Please describe.**
I want to create some custom armor items with my code. But when i try, it doesn't really works.

**Describe the solution you'd like**
Make something (if possible) that allows you to have the model of the armor on you, but if already made, please explain it.

**Describe alternatives you've considered**
Make it so in code, you have to specify the textures to the armor's models.

**Additional context**
If its already working, please explain me

**Comment by alvin0319** [comment]
Armor will not implemented in future, because of idot client.
