### ISSUE TITLE
Eating food cause client crash -> When looking at block and right click

### ISSUE THREAD

**Issue by benda95280** [alvin0319/CustomItemLoader#29]
**Describe the bug**
When trying to eat food, client crash when looking at block and right click

**To Reproduce**
1a. Tried with example facebook item
2b. Tried with custom item
3. Look at a block and eat the item

**Expected behavior**
Client should no crash

**Actual behavior**
Client game close unexpectedly

**Screenshots**
N/A

**Version info (please complete the following information):**

 - OS: W10
 - PocketMine-MP Version: 3.19.0 / 3.19.1
 - CustomItemLoader Version: Lastest from Github

**Additional context**

**Comment by alvin0319** [comment]
Example resource pack can cause crash because of its pixel amount.

**Comment by RutabagaCraft** [comment]
Have you been able to reproduce it on your side ? Tried with custom item, same, tried without texture too ... same.

**Comment by RutabagaCraft** [comment]
Fixed myself, thanks

**Comment by Nya-Enzo** [comment]
How did you fix it ?
