### ISSUE TITLE
Item do not show in hand

### ISSUE THREAD

**Issue by Adam1609** [alvin0319/CustomItemLoader#3]
![Minecraft 12_21_2020 11_56_08 AM](https://user-images.githubusercontent.com/16860075/102740958-a69cc200-4383-11eb-8598-2fcfa62ac917.png)

Here is my config:

`items:
  battleaxe:
    id: 1001
    meta: 0
    namespace: "custom:battleaxe"
    name: battleaxe
    allow_off_hand: true
    max_stack_size: 1
    texture: battleaxe
    durable: true
    max_durability: 64
    mining_speed: 10`

I have make a pack and put it in the main resource pack folder.

**Comment by BLAST1718** [comment]
did u put the right name?

**Comment by Adam1609** [comment]
Yes I put the right name of the texture pack. I will try to find out the things I do wrong

**Comment by BLAST1718** [comment]
oh it must be on the plugin

**Comment by Adam1609** [comment]
Oh I found out the things I do wrong, missing argument in item_texture.json. Will close this issue now

**Comment by alvin0319** [comment]
use /rsc for creating resource packs
