### ISSUE TITLE
Class ItemTypeDictionary does not exist

### ISSUE THREAD

**Issue by iteplenky** [alvin0319/CustomItemLoader#31]
**Describe the bug**
ReflectionException: "Class "pocketmine\network\mcpe\convert\ItemTypeDictionary" does not exist" (-1) in "plugins/customitems/src/alvin0319/CustomItemLoader/CustomItemLoader" at line 81

**To Reproduce**
1. update pm

**Expected behavior**
plugin work

**Actual behavior**
Class "pocketmine\network\mcpe\convert\ItemTypeDictionary" does not exist

**Screenshot**
![image](https://user-images.githubusercontent.com/42160062/120101561-6a5a6280-c168-11eb-9b7e-5833afe0ec23.png)

**Version info (please complete the following information):**

 - OS: dsnt matter
 - PocketMine-MP Version: latest
 - CustomItemLoader Version: latest pm4

**Comment by alvin0319** [comment]
Thank you for reporting bug. I'll fix it as soon as possible.
