### ISSUE TITLE
the plugin went BRRR

### ISSUE THREAD

**Issue by IcyEndymion004** [alvin0319/CustomItemLoader#36]
08.06 15:40:02 [Server] CRITICAL InvalidArgumentException: "Unmapped ID/metadata combination 1002:0" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/convert/ItemTranslator" at line 157
08.06 15:40:02 [Server] CRITICAL #0 pmsrc/src/pocketmine/network/mcpe/NetworkBinaryStream(305): pocketmine\network\mcpe\convert\ItemTranslator->toNetworkId(integer 1002, integer 0)
08.06 15:40:02 [Server] CRITICAL #1 pmsrc/src/pocketmine/network/mcpe/protocol/types/inventory/ItemStackWrapper(66): pocketmine\network\mcpe\NetworkBinaryStream->putItemStack(object pocketmine\item\Item, object Closure)
08.06 15:40:02 [Server] CRITICAL #2 pmsrc/src/pocketmine/network/mcpe/protocol/MobEquipmentPacket(55): pocketmine\network\mcpe\protocol\types\inventory\ItemStackWrapper->write(object pocketmine\network\mcpe\protocol\MobEquipmentPacket)
08.06 15:40:02 [Server] CRITICAL #3 pmsrc/src/pocketmine/network/mcpe/protocol/DataPacket(127): pocketmine\network\mcpe\protocol\MobEquipmentPacket->encodePayload()
08.06 15:40:02 [Server] CRITICAL #4 pmsrc/src/pocketmine/Server(1705): pocketmine\network\mcpe\protocol\DataPacket->encode()
08.06 15:40:02 [Server] CRITICAL #5 pmsrc/src/pocketmine/inventory/PlayerInventory(179): pocketmine\Server->broadcastPacket(array[0], object pocketmine\network\mcpe\protocol\MobEquipmentPacket)
08.06 15:40:02 [Server] CRITICAL #6 pmsrc/src/pocketmine/inventory/PlayerInventory(140): pocketmine\inventory\PlayerInventory->sendHeldItem(array[0])

brand new pocketmine verion for 1.17
and newest custom item loader LOL

**Comment by brokiem** [comment]
Dude why did you modify mcpe-protocol in plugin.yml, it won't work.

**Comment by KygekDev** [comment]
> Dude why did you modify mcpe-protocol in plugin.yml, it won't work.

It won't work only if there is/are breaking protocol change(s) in Minecraft and PocketMine-MP which affects the plugin.

**Comment by alvin0319** [comment]
modifing plugin.yml without changes will **NOT** help you from helping this plugin work. also read the wiki and try again. it was caused by your wrong config configuration
