### ISSUE TITLE
Damage

### ISSUE THREAD

**Issue by yangyong080228** [alvin0319/CustomItemLoader#40]
**Is your feature request related to a problem? Please describe.**
Editable Damage Value and item desc

**Describe the solution you'd like**
it for custom weapon ye

**Describe alternatives you've considered**
idk

**Additional context**
idk

**Comment by alvin0319** [comment]
Damage is already implemented in durable property.

**Comment by yangyong080228** [comment]
huh? like
`/give player item:(dmg)` this? not working :/
