### ISSUE TITLE
Is not normal

### ISSUE THREAD

**Issue by Willtom999** [alvin0319/CustomItemLoader#42]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what you experienced.

**Screenshots**

**Version info (please complete the following information):**

 - PocketMine-MP Version:
 - CustomItemLoader Version:

**Additional context**

**Comment by Willtom999** [comment]
![bug3](https://user-images.githubusercontent.com/83521998/125171904-c01d2400-e184-11eb-999f-06807ff46b5d.png)

**Comment by alvin0319** [comment]
Not enough information
