### ISSUE TITLE
Problem with durability

### ISSUE THREAD

**Issue by Bqleine** [alvin0319/CustomItemLoader#43]
**Describe the bug**
When using a custom durability on an item, the durability bar is bugged

**To Reproduce**
1. Use the example
2. Set the  config to : 
```items:
  facebook:
    id: 1001
    meta: 0
    namespace: "custom:facebook"
    name: facebook
    allow_off_hand: true
    max_stack_size: 1
    texture: facebook
    durable: true
    max_durability: 10
    mining_speed: 10
    food: false
    can_always_eat: true
    nutrition: 10
    saturation: 2
```
3. Break blocks with the item

**Expected behavior**
The durability bar goes down progressively as I destroy blocks

**Actual behavior**
The durability bar shows 0 durability

**Screenshots**
![image](https://user-images.githubusercontent.com/51089082/126063677-60131cde-c974-415e-b97d-6a07a683a243.png)

**Version info (please complete the following information):**
 - OS: Windows 10
 - PocketMine-MP Version: 3.22.0
 - CustomItemLoader Version: 2.0.7

**Comment by alvin0319** [comment]
This will not fixed in future, I'm going to close this.
