### ISSUE TITLE
Display mode

### ISSUE THREAD

**Issue by Steellgold** [alvin0319/CustomItemLoader#48]
**What is your question? describe it simplify and clear**

How can we display the item in "food" mode as for example a compass it is in the hand and not in tool mode

![image](https://user-images.githubusercontent.com/51505384/128630432-5430669d-4ad2-460f-9340-9fddbffae7e6.png)
![image](https://user-images.githubusercontent.com/51505384/128630442-d13e3e1e-6854-4ebb-a2d9-b77cd11c0307.png)
![image](https://user-images.githubusercontent.com/51505384/128630479-419e60ad-9543-460b-b967-7fb007f34ed3.png)
![image](https://user-images.githubusercontent.com/51505384/128630470-770594be-2ce0-44fc-b3a0-44aa3578aeb7.png)

**Comment by alvin0319** [comment]
use `hand_equipped`

**Comment by Steellgold** [comment]
i'm go test

**Comment by Steellgold** [comment]
hand_equiped: true is for ? because when I put true or false it always stays in tool mode

**Comment by Steellgold** [comment]
![image](https://user-images.githubusercontent.com/51505384/128631697-5d16f285-b072-48ad-8e6f-16e2e13cd016.png)

**Comment by evilldark** [comment]
Hand_equiped ir hand_equipped?

**Comment by alvin0319** [comment]
`hand_equipped` is correct.
