### ISSUE TITLE
how to register from plugin

### ISSUE THREAD

**Issue by Doxestic** [alvin0319/CustomItemLoader#51]
**What is your question? describe it simplify and clear**
how to register item from plugin?
i adds resources for it but how to do it it gives error getPro.. function

**Comment by RealBJsingh** [comment]
Please send the full error

**Comment by Doxestic** [comment]
pocketmine\utils\AssumptionFailedError: "Failed to register item: Call to undefined method pocketmine\item\Item::getProperties()" (109) in "plugins/CustomItemLoader-master/src/alvin0319/CustomItemLoader/CustomItemManager" at line 123

**Comment by alvin0319** [comment]
You have to use `CustomItemTrait`
