### ISSUE TITLE
why this happens?

### ISSUE THREAD

**Issue by Doxestic** [alvin0319/CustomItemLoader#54]
**Describe the bug**
how to fix it?
![Screenshot (419)](https://user-images.githubusercontent.com/63596588/129486452-274549f4-bfad-4ab7-b01c-ebf9c387409b.png)

code: 
CustomItemManager::getInstance()->registerItem(CustomItemManager::getItem("$name", ["name" => "$name", "namespace" => "minecraft:$name", "id" => $info["id"], "meta" => 0, "texture" => "minecraft:$name", "hand_equipped" => true, "nutrition" => 10, "saturation" => 2]), false);
(last false is for a small edit to dont register files that i dont want)

**Comment by Steellgold** [comment]
is the texture pack you must be texture 16x16

**Comment by alvin0319** [comment]
You have to use 16x16 texture size. also, I suggest that don't use `minecraft` prefix on item namespace in order to prevent any conflicts from mcbe client.
