### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by Steellgold** [alvin0319/CustomItemLoader#57]
Hello, when Right Click in Item who "always_eat" or "food" as a true, the Minecraft Client Crash

**Comment by Steellgold** [comment]
Forgot to specify when you click right on a block

**Comment by Steellgold** [comment]
Tip: It with all items on rigth click in a block

**Comment by evilldark** [comment]
I add textures and items in config.yml but when I try to get the item, it
comes without texture even with the texture in resource_packs folder and
resource_packs config

Em Sex, 27 de ago de 2021 18:35, Gaëtan H ***@***.***>
escreveu:
