### ISSUE TITLE
Armor Slots

### ISSUE THREAD

**Issue by Nya-Enzo** [alvin0319/CustomItemLoader#60]
**Describe the bug**
In the feature\armor branch, you made a commit for armors slots saying "working but wierd", but when trying it, didn't work.

**To Reproduce**
1. Add own custom item
2. Go on server
3. Get the custom item
4. See that you can't put it in chest slot

**Expected behavior**
I was expecting to the item to just put in the chestplate slot

**Actual behavior**
It actually clearly showed that you can't make any transaction making the item go in the chestplate slot

**Screenshots**
Sorry, i don't have any

**Version info (please complete the following information):**

 - OS: Windows 10
 - PocketMine-MP Version: 3.22.2
 - CustomItemLoader Version: feature\armor branch, commit 18ab6ff596ea3e8a8b8972801940cab666c889c8

**Additional context**
If it is possible, i would know what im doing wrong

**Comment by alvin0319** [comment]
Armor branch isn't supported.
