### ISSUE TITLE
Texture and name bugged

### ISSUE THREAD

**Issue by ByLex-69bits** [alvin0319/CustomItemLoader#61]
I use this plugin on a host server at HostMyServer, however at launch I have this sentence that appears: [CustomItemLoader] Detected this server isn't running on 19132 port. If you are running this server behind proxy, make sure to use this plugin on lobby.  And the textures and names don't appear correctly (the texure pack doesn't affect), so I'd like to know if I just have to go through the port in 1932 for it to work.

**Comment by HydroGames-dev** [comment]
This isn't a bug
Intended feature
[Check the code here](https://github.com/alvin0319/CustomItemLoader/blob/5326885b732c3f17cefcd7f2c800fe4161599ecc/src/alvin0319/CustomItemLoader/CustomItemLoader.php#L58) 

use the port 19132 for the server for it to run

**Comment by alvin0319** [comment]
> [CustomItemLoader] Detected this server isn't running on 19132 port. If you are running this server behind proxy, make sure to use this plugin on lobby.

This means be careful if you are using proxy with your servers. If not, check the config.
