### ISSUE TITLE
Call undefined method (CustomItemLoader.php line 50)

### ISSUE THREAD

**Issue by NguyenDuck** [alvin0319/CustomItemLoader#62]
https://github.com/alvin0319/CustomItemLoader/blob/a0731acbcf0d455a558c8f3859d186674619957f/src/alvin0319/CustomItemLoader/CustomItemLoader.php#L50

**Comment by alvin0319** [comment]
Which version(branch) do you use?

**Comment by NguyenDuck** [comment]
I'm using default branch

**Comment by NguyenDuck** [comment]
PMMP API 3.22.5

**Comment by alvin0319** [comment]
default branch is for PM4, you have to use `master` branch. But anyway I've found the error, Thank you for reporting bug.
