### ISSUE TITLE
Error in lancement

### ISSUE THREAD

**Issue by ByLex-69bits** [alvin0319/CustomItemLoader#69]
i delete this protocol line to get acces to the plugin but when i past the exemple item in the config i have this at the lancement.
[Server thread/CRITICAL]: ParseError: "syntax error, unexpected '=>' (T_DOUBLE_ARROW)" (EXCEPTION) in "plugins/CustomItemLoader-master/src/alvin0319/CustomItemLoader/item/properties/CustomItemProperties" at line 125

**Comment by alvin0319** [comment]
You have to use PHP 8.0 or higher in order to use this plugin. also, don't modify plugin.yml yourself to remove `mcpe-protocol` or `extensions` field. It doesn't help you from working plugin.
