### ISSUE TITLE
Couldn’t load it

### ISSUE THREAD

**Issue by UnknownCkd** [alvin0319/CustomItemLoader#73]
When i start my server i have protocole error or php core 8 error, so im a little beat stuck. So pls who can i patch this plss

**Comment by HydroGames-dev** [comment]
Install the PHP Binary to 8.0

**Comment by HydroGames-dev** [comment]
You have to use PHP 8.0 or higher version in order to use CustomItemLoader. (because I used PHP8 grammar.)

_Originally posted by @alvin0319 in https://github.com/alvin0319/CustomItemLoader/issues/66#issuecomment-927007577_

**Comment by alvin0319** [comment]
Request to the hoster to add PHP8 option (in my case, I made ticket that request support PHP 7.4 binary when php 7.4 was released, and it got approved on Ramshard)
