### ISSUE TITLE
item name

### ISSUE THREAD

**Issue by ByLex-69bits** [alvin0319/CustomItemLoader#78]
I don't understand why, but i add a new line to .US to add the item name but if doesn't work :
item.astral.name=Astral  #

**Comment by DidntPot** [comment]
is it doesn't work then the item should have a default name like `custom.item` then just put this in .lang `custom.item=§bBat`.

**Comment by Dyntes** [comment]
Are you sure you put it in en_US.lang inside a resource pack? and put it like "item.<namespace>.name = <display name>" inside it?
