### ISSUE TITLE
Custom Item does not appear on Village Trade screen

### ISSUE THREAD

**Issue by Adam1609** [alvin0319/CustomItemLoader#8]
I have been trying implement the custom item that I have just created into the trade. But apparently it doesn't show in the menu. I try both V1 and V2 but still not work. Is it cause by game or smth?

**Comment by alvin0319** [comment]
Can you provide some screenshot? I can't understand

**Comment by Adam1609** [comment]
I don't have any screenshot. But when I use your TradeNPC plugin, setting both slot 1 and slot 2 will not appear on Trade screen

**Comment by alvin0319** [comment]
TradeNPC plugin is now discontinued.
