### ISSUE TITLE
Bug texture

### ISSUE THREAD

**Issue by Willtom999** [alvin0319/CustomItemLoader#83]
Texture Is buged
![37AFE6F9-5B59-4D4A-83D2-B5E85A448673](https://user-images.githubusercontent.com/83521998/146980976-8681ed3d-10e8-4beb-ba2e-bf058a638f7d.png)
![9C3265D9-1A3F-4C4C-A9F6-1B2A8FEDD1A8](https://user-images.githubusercontent.com/83521998/146980984-e8b88484-2f39-4059-a698-62208d037e73.png)

**Comment by alvin0319** [comment]
duplicate of #18, #44
