### ISSUE TITLE
Armor bug

### ISSUE THREAD

**Issue by MrSquid1yt** [alvin0319/CustomItemLoader#87]
Armor is not displaying in the Inventory and no armor defensepoints over the hotbar see screenshots
(and it dont add to the Creative inv)
 - OS: Windows
 - PocketMine-MP Version: 4.0.3
 - CustomItemLoader Version: 2.3.0 
My Config:
https://paste-bin.xyz/29368

![grafik](https://user-images.githubusercontent.com/59023075/147833434-c96d4168-984b-419c-9132-de36c4cf356a.png)
![grafik](https://user-images.githubusercontent.com/59023075/147833454-c6242a60-9495-4405-98ae-21da69e8141a.png)

**Comment by ByLex-69bits** [comment]
its not a bug itsur texture pack, u dont add ur model armor texture

**Comment by alvin0319** [comment]
You didn't add the armor model to your texture pack, as above said.
