### ISSUE TITLE
Minimum number of properties sent to Client

### ISSUE THREAD

**Issue by TheBlackPlague** [alvin0319/CustomItemLoader#91]
I'm wondering what the minimum properties are that need to be sent to the client for the client to render the texture. I know you send a bunch, but I'm trying to abstract whatever network-nbt properties are necessary for a regular item (not food or armor or block) to be rendered on the client (not have an invisible texture). 

If you can provide more information on top of this, it would be greatly appreciated.

**Comment by TheBlackPlague** [comment]
Furthermore, do custom items have to be one of these? [CONFIGURATION.md#templates](https://github.com/alvin0319/CustomItemLoader/blob/c3dd9bbbf1fdab718951033610cd5a6a02104608/CONFIGURATION.md#templates)

**Comment by alvin0319** [comment]
Closed in 1a6ce4bd5932aa77ad08abfd3ac7f15e5d26611f
