### ISSUE TITLE
Cooldown feature ?

### ISSUE THREAD

**Issue by dadodasyra** [alvin0319/CustomItemLoader#93]
**Is your feature request related to a problem? Please describe.**
No client side cooldown available

**Describe the solution you'd like**
Add the component for cooldown like ender pearl

**Additional context**
I'm not sure if it's possible but don't seems impossible too

**Comment by alvin0319** [comment]
Closed via 83689c185ec32c93a7bbebb1dd6a60d7f8c191a0
